name: CI/CD Pipeline

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Build Frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run build

      - name: Build Backend Docker Image
        run: docker build -t intelligent-tax-app-backend ./backend

      - name: Build Frontend Docker Image
        run: docker build -t intelligent-tax-app-frontend ./frontend

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        working-directory: backend
        run: pip install -r requirements.txt

      - name: Run Tests
        working-directory: backend
        run: python -m pytest
